# Generated by Django 5.1.4 on 2025-01-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="age",
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="team",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
