# Generated by Django 5.1.4 on 2025-01-02 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_player_age_alter_team_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AlterField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team",
                to="backend.team",
            ),
        ),
    ]
